/**
 * codex/handler.tmpl.ts — string-constant source of truth for the
 * Codex hook handler script.
 *
 * The string exported as `HANDLER_SOURCE` is the full self-contained
 * `.mjs` source for the generated `.codex/hooks/bp-handler.mjs` file.
 * `src/integrations/codex/handler.ts` re-exports this constant and
 * surfaces the testable handlers (isDisabled, hasBpConfig, etc.).
 *
 * Byte-determinism: this constant MUST NOT include Date.now(),
 * Math.random(), or any environment lookups. Two reads of HANDLER_SOURCE
 * are guaranteed identical and two calls to generateCodexHandler()
 * with the same config return identical content.
 *
 * Runtime contract:
 *   - BP_HOOKS=0 OR BP_DISABLE_HOOKS=1  -> exit 0 silently (bypass)
 *   - missing bp/config.yaml            -> exit 0 silently (bypass)
 *   - SessionStart                      -> emit <bp-context> payload
 *   - UserPromptSubmit                  -> emit bp-workflow-state payload
 *   - PreToolUse                        -> emit bp-workflow-state payload
 *   - PostToolUse                       -> emit bp-workflow-state payload
 *   - SessionStop                       -> no-op (exit 0)
 */

export const HANDLER_SOURCE = `#!/usr/bin/env node
// bp Codex handler - generated by bp update. Do not edit manually.
// Implements the bp runtime contract for Codex v0.140+ hooks.
//
// Event mapping (all dispatched with the event name as argv[2]):
//   SessionStart     -> <bp-context> block
//   UserPromptSubmit -> bp-workflow-state payload
//   PreToolUse       -> bp-workflow-state payload (matcher: Bash)
//   PostToolUse      -> bp-workflow-state payload (matcher: Bash)
//   SessionStop      -> no-op (exit 0)
//
// Bypass:
//   BP_HOOKS=0 or BP_DISABLE_HOOKS=1 -> exit 0 silently
//   missing bp/config.yaml           -> exit 0 silently

import { existsSync, readFileSync } from "node:fs";
import { join } from "node:path";

function isDisabled() {
  return process.env.BP_HOOKS === "0" || process.env.BP_DISABLE_HOOKS === "1";
}

function hasBpConfig(cwd) {
  if (!cwd) return false;
  return existsSync(join(cwd, "bp", "config.yaml"));
}

function readBpState(cwd) {
  try {
    var out = readFileSync(join(cwd, "bp", "state.md"), "utf-8");
    return out.trim() || "_no state available_";
  } catch {
    return "_no state available_";
  }
}

function generateContextBlock(cwd) {
  if (!cwd || !hasBpConfig(cwd)) {
    return "<bp-context>\\n</bp-context>";
  }
  return "<bp-context>\\n</bp-context>";
}

function generateWorkflowState(cwd) {
  return readBpState(cwd);
}

function bypass() {
  return { continue: true };
}

function contextPayload(block) {
  return {
    continue: true,
    hookSpecificOutput: {
      hookEventName: "SessionStart",
      additionalContext: block,
    },
  };
}

function statePayload(event, state) {
  return {
    continue: true,
    hookSpecificOutput: {
      hookEventName: event,
      additionalContext: state,
    },
  };
}

function dispatch(event, cwd) {
  if (event === "SessionStart") {
    return contextPayload(generateContextBlock(cwd));
  }
  if (event === "UserPromptSubmit" || event === "PreToolUse" || event === "PostToolUse") {
    return statePayload(event, generateWorkflowState(cwd));
  }
  return bypass();
}

var event = process.argv[2] || "";
var cwd = process.cwd();

if (isDisabled() || !hasBpConfig(cwd)) {
  process.stdout.write(JSON.stringify(bypass()) + "\\n");
} else {
  process.stdout.write(JSON.stringify(dispatch(event, cwd)) + "\\n");
}
`;