/**
 * bp update — 更新平台文件（commands + agents + skills）
 */

import { join } from 'node:path';
import { mkdirSync, writeFileSync } from 'node:fs';
import { loadConfig } from '../core/config.js';
import { generateAll } from '../generators/index.js';
import { writeGeneratedFiles } from './_utils.js';

const HOOK_TEMPLATE = `/**
 * bp OMP Hook — automated spec injection and workflow guidance.
 * Generated by bp update. Do not edit manually.
 */
import { existsSync } from "node:fs";
import { join } from "node:path";
import { execSync } from "node:child_process";

export default function bpHook(api: any): void {
  api.on("session_start", async (_event: any, ctx: any) => {
    const cwd = ctx.cwd ?? process.cwd();
    if (!existsSync(join(cwd, "bp", "state.md"))) return;
    try {
      const output = execSync("bp context current", { cwd, encoding: "utf-8", timeout: 5000 });
      const data = JSON.parse(output);
      const lines: string[] = [];
      lines.push(\`[bp] Project: \${data.project} | Status: \${data.status}\`);
      if (data.specs?.length) {
        lines.push("\\n─── Specs ───");
        for (const spec of data.specs) {
          if (spec.content) lines.push(\`\\n### \${spec.path}\\n\${spec.content.slice(0, 4096)}\`);
        }
      }
      if (data.conventions?.length) {
        lines.push("\\n─── Conventions ───");
        for (const conv of data.conventions) {
          if (conv.content) lines.push(\`\\n### \${conv.path}\\n\${conv.content.slice(0, 2048)}\`);
        }
      }
      api.sendMessage({ role: "custom", customType: "bp-session", content: [{ type: "text", text: lines.join("\\n") }], timestamp: Date.now() });
    } catch { /* bp CLI not available */ }
  });

  // ── Quality gate: warn on test/lint/typecheck failures ──
  api.on("tool_result", async (event: any) => {
    if (event.isError || event.toolName !== "bash") return;
    const cmd = String(event.input?.command ?? "");
    const isCheck = /\b(vitest|jest|tsc\b|typecheck|eslint|prettier.*--check)\b/.test(cmd);
    if (!isCheck) return;
    const text = String(event.content?.[0]?.text ?? "");
    const m = text.match(/exited with code (\d+)/i);
    if (m && parseInt(m[1]) !== 0) {
      api.sendMessage({ role: "custom", customType: "bp-quality-gate", content: [{ type: "text", text: \`[bp] Quality gate FAILED: \${cmd.trim().split("\\n")[0]}\\nFix failures before running bp continue.\` }], timestamp: Date.now() }, { deliverAs: "followUp" });
    }
  });

  api.on("before_agent_start", async (_event: any, ctx: any) => {
    const cwd = ctx.cwd ?? process.cwd();
    if (!existsSync(join(cwd, "bp", "state.md"))) return;
    try {
      const output = execSync("bp state", { cwd, encoding: "utf-8", timeout: 3000 });
      const state = JSON.parse(output);
      const pending = state.pending || [];
      const hint = pending.length > 0
        ? \`[bp] Pending: \${pending.map((p: any) => \`\${p.name}[\${p.status}]\`).join(", ")}. Run bp continue.\`
        : \`[bp] Status: \${state.status}. Run bp continue.\`;
      ctx.ui?.setStatus?.("bp", hint);
    } catch { /* skip */ }
  });
}
`;

export function register(program: any): void {
  program
    .command('update')
    .description('Regenerate platform files (commands + agents + skills + hooks)')
    .option('--dir <path>', 'bp directory', 'bp')
    .action(updateHandler);
}

function updateHandler(options: { dir: string }) {
  const bpDir = join(process.cwd(), options.dir);

  const config = loadConfig(bpDir);
  const files = generateAll(config);

  console.log('Regenerating platform files...');
  writeGeneratedFiles(files);

  // Deploy OMP hook
  const hookDir = join(process.cwd(), '.omp', 'hooks', 'pre');
  mkdirSync(hookDir, { recursive: true });
  writeFileSync(join(hookDir, 'bp.ts'), HOOK_TEMPLATE, 'utf-8');
  console.log('  ✓ .omp/hooks/pre/bp.ts');

  console.log(`✓ Update complete (${files.length + 1} files)`);
}
