/**
 * bp update — 更新平台文件（commands + agents + hooks）
 */

import { join } from 'node:path';
import { mkdirSync, writeFileSync, rmSync, readdirSync, existsSync } from 'node:fs';
import { Command } from 'commander';
import { loadConfig } from '../core/config.js';
import { generateAll } from '../generators/index.js';
import { PlatformRegistry } from '../core/platform-registry.js';
import { writeGeneratedFiles } from './_utils.js';

const HOOK_TEMPLATE = `/**
 * bp OMP Hook — automated workflow state injection.
 * Generated by bp update. Do not edit manually.
 */
import { existsSync } from "node:fs";
import { join } from "node:path";
import { execSync } from "node:child_process";

export default function bpHook(api: { on: (e: string, h: (ev: unknown, ctx: unknown) => unknown) => void; sendMessage: (m: unknown, o?: unknown) => void }): void {
  api.on("session_start", async (_event: unknown, ctx: unknown) => {
    const cwd = (ctx as Record<string, unknown> | null)?.cwd;
    const workDir = typeof cwd === "string" ? cwd : process.cwd();
    if (!existsSync(join(workDir, "bp", "state.md"))) return;
    try {
      const output = execSync("bp state", { cwd: workDir, encoding: "utf-8", timeout: 5000 });
      const state = JSON.parse(output) as { project?: string; status?: string; milestone?: string | null; phase?: string | null };
      const lines: string[] = [];
      lines.push(\`[bp] Project: \${state.project ?? "-"} | Status: \${state.status ?? "-"}\`);
      if (state.milestone) lines.push(\`Milestone: \${state.milestone}\`);
      if (state.phase) lines.push(\`Phase: \${state.phase}\`);
      lines.push("Run \\\`bp context <step>\\\` for specs/conventions injection.");
      api.sendMessage({ role: "custom", customType: "bp-session", content: [{ type: "text", text: lines.join("\\n") }], timestamp: Date.now() });
    } catch { /* bp CLI not available */ }
  });

  api.on("before_agent_start", async (_event: unknown, ctx: unknown) => {
    const cwd = (ctx as Record<string, unknown> | null)?.cwd;
    const workDir = typeof cwd === "string" ? cwd : process.cwd();
    if (!existsSync(join(workDir, "bp", "state.md"))) return;
    try {
      const output = execSync("bp state", { cwd: workDir, encoding: "utf-8", timeout: 3000 });
      const state = JSON.parse(output) as { pending?: Array<{ name: string; status: string }>; status?: string };
      const pending = state.pending ?? [];
      const hint = pending.length > 0
        ? \`[bp] Pending: \${pending.map((p) => \`\${p.name}[\${p.status}]\`).join(", ")}. Run \\\`bp continue\\\`.\`
        : \`[bp] Status: \${state.status ?? "-"}. Run \\\`bp continue\\\`.\`;
      const ui = (ctx as Record<string, unknown> | null)?.ui;
      if (ui && typeof ui === "object" && "setStatus" in ui) {
        (ui as { setStatus: (l: string, v: string) => void }).setStatus("bp", hint);
      }
    } catch { /* skip */ }
  });
}
`;

/** Remove stale generated files that no longer exist in the generation set. */
function cleanupStaleFiles(baseDir: string, generatedPaths: string[]): void {
  const generatedSet = new Set(generatedPaths.map(p => p.replace(/^\.\//, '')));

  // Cleanup stale commands
  const cmdDir = join(baseDir, '.omp', 'commands');
  if (existsSync(cmdDir)) {
    for (const file of readdirSync(cmdDir)) {
      const relPath = `.omp/commands/${file}`;
      if (!generatedSet.has(relPath)) {
        rmSync(join(cmdDir, file));
        console.log(`  ✓ Removed stale: ${relPath}`);
      }
    }
  }

  // Cleanup stale skills (entire dir if skills are skipped)
  const skillsDir = join(baseDir, '.omp', 'skills');
  const ompCaps = PlatformRegistry.has('omp') ? PlatformRegistry.resolve('omp').capabilities : undefined;
  const ompSupportsCommands = ompCaps?.supportsCommands ?? true;
  if (existsSync(skillsDir) && ompSupportsCommands) {
    rmSync(skillsDir, { recursive: true, force: true });
    console.log('  ✓ Removed stale: .omp/skills/ (platform supports commands)');
  }
}

export function register(program: Command): void {
  program
    .command('update')
    .description('Regenerate platform files (commands + agents + hooks)')
    .option('--dir <path>', 'bp directory', 'bp')
    .action(updateHandler);
}

function updateHandler(options: { dir: string }) {
  const bpDir = join(process.cwd(), options.dir);
  const cwd = process.cwd();

  const config = loadConfig(bpDir);
  const files = generateAll(config);
  const generatedPaths = files.map(f => f.path);

  console.log('Regenerating platform files...');
  writeGeneratedFiles(files);

  // Cleanup stale files
  cleanupStaleFiles(cwd, generatedPaths);

  // Deploy OMP hook
  const hookDir = join(cwd, '.omp', 'hooks', 'pre');
  mkdirSync(hookDir, { recursive: true });
  writeFileSync(join(hookDir, 'bp.ts'), HOOK_TEMPLATE, 'utf-8');
  console.log('  ✓ .omp/hooks/pre/bp.ts');

  console.log(`✓ Update complete (${files.length + 1} files)`);
}
