/**
 * bp update — 更新平台文件（commands + agents + hooks）
 */

import { join } from 'node:path';
import { mkdirSync, writeFileSync, rmSync, readdirSync, existsSync } from 'node:fs';
import { Command } from 'commander';
import { loadConfig } from '../core/config.js';
import { generateAll } from '../generators/index.js';
import { PlatformRegistry } from '../core/platform-registry.js';
import { writeGeneratedFiles } from './_utils.js';

export const HOOK_TEMPLATE = `/**
 * bp OMP Hook - artifact-based progress injection.
 * Generated by bp update. Do not edit manually.
 */
import { existsSync } from "node:fs";
import { join } from "node:path";
import { execSync } from "node:child_process";

export default function bpHook(api: { on: (e: string, h: (ev: unknown, ctx: unknown) => unknown) => void; sendMessage: (m: unknown, o?: unknown) => void }): void {
  api.on("session_start", async (_event: unknown, ctx: unknown) => {
    const cwd = (ctx as Record<string, unknown> | null)?.cwd;
    const workDir = typeof cwd === "string" ? cwd : process.cwd();
    if (!existsSync(join(workDir, "bp", "config.yaml"))) return;
    try {
      const output = execSync("bp continue", { cwd: workDir, encoding: "utf-8", timeout: 5000 });
      const lines = output.trim().split("\\n").slice(0, 8);
      api.sendMessage({ role: "custom", customType: "bp-session", content: [{ type: "text", text: lines.join("\\n") }], timestamp: Date.now() });
    } catch { /* bp CLI not available */ }
  });

  api.on("before_agent_start", async (_event: unknown, ctx: unknown) => {
    const cwd = (ctx as Record<string, unknown> | null)?.cwd;
    const workDir = typeof cwd === "string" ? cwd : process.cwd();
    if (!existsSync(join(workDir, "bp", "config.yaml"))) return;
    try {
      const output = execSync("bp continue", { cwd: workDir, encoding: "utf-8", timeout: 3000 });
      const hint = output.trim().split("\\n").find((l: string) => l.startsWith("Next:")) ?? "[bp] Run bp continue for status.";
      const ui = (ctx as Record<string, unknown> | null)?.ui;
      if (ui && typeof ui === "object" && "setStatus" in ui) {
        (ui as { setStatus: (l: string, v: string) => void }).setStatus("bp", hint);
      }
    } catch { /* skip */ }
  });
}
`;

/** Remove stale generated files that no longer exist in the current v2 generation set. */
function cleanupStaleFiles(baseDir: string, generatedPaths: string[]): void {
  const generatedSet = new Set(generatedPaths.map(p => p.replace(/^\.\//, '')));

  // V2 step names for directory-based check (.agent/skills/ entries don't match generatedSet directly)
  const v2Steps: Record<string, true> = { init: true, roadmap: true, propose: true, plan: true, apply: true, review: true, archive: true, continue: true, ff: true, loop: true };

  // Helper: remove a single file if it isn't in the generated set
  function checkRemove(dir: string, relPrefix: string, file: string): void {
    // Only touch BP files (bp-* prefix), leave other tools' files alone
    if (!file.startsWith('bp-')) return;
    const relPath = `${relPrefix}/${file}`;
    if (!generatedSet.has(relPath)) {
      rmSync(join(dir, file));
      console.log(`  ✓ Removed stale: ${relPath}`);
    }
  }

  // .omp/commands/
  const ompCmdDir = join(baseDir, '.omp', 'commands');
  if (existsSync(ompCmdDir)) {
    for (const file of readdirSync(ompCmdDir)) {
      checkRemove(ompCmdDir, '.omp/commands', file);
    }
  }

  // .omp/agents/
  const ompAgentDir = join(baseDir, '.omp', 'agents');
  if (existsSync(ompAgentDir)) {
    for (const file of readdirSync(ompAgentDir)) {
      checkRemove(ompAgentDir, '.omp/agents', file);
    }
  }

  // .omp/skills/ — only remove stale bp-* skills, leave other tools' skills alone
  const ompSkillsDir = join(baseDir, '.omp', 'skills');
  if (existsSync(ompSkillsDir)) {
    for (const file of readdirSync(ompSkillsDir)) {
      checkRemove(ompSkillsDir, '.omp/skills', file);
    }
  }

  // .claude/commands/
  const claudeCmdDir = join(baseDir, '.claude', 'commands');
  if (existsSync(claudeCmdDir)) {
    for (const file of readdirSync(claudeCmdDir)) {
      checkRemove(claudeCmdDir, '.claude/commands', file);
    }
  }

  // .claude/agents/
  const claudeAgentDir = join(baseDir, '.claude', 'agents');
  if (existsSync(claudeAgentDir)) {
    for (const file of readdirSync(claudeAgentDir)) {
      checkRemove(claudeAgentDir, '.claude/agents', file);
    }
  }

  // .agent/skills/ — entries are directories like bp-<step>/
  const agentSkillsDir = join(baseDir, '.agent', 'skills');
  if (existsSync(agentSkillsDir)) {
    for (const entry of readdirSync(agentSkillsDir)) {
      // Extract step name from "bp-<step>" directory name
      const match = /^bp-(.+)$/.exec(entry);
      if (match && !v2Steps[match[1]]) {
        rmSync(join(agentSkillsDir, entry), { recursive: true, force: true });
        console.log(`  ✓ Removed stale: .agent/skills/${entry}/`);
      }
    }
  }

  // .agent/agents/
  const agentAgentDir = join(baseDir, '.agent', 'agents');
  if (existsSync(agentAgentDir)) {
    for (const file of readdirSync(agentAgentDir)) {
      checkRemove(agentAgentDir, '.agent/agents', file);
    }
  }
}

export function register(program: Command): void {
  program
    .command('update')
    .description('Regenerate platform files (commands + agents + hooks)')
    .option('--dir <path>', 'bp directory', 'bp')
    .action(updateHandler);
}

function updateHandler(options: { dir: string }) {
  const bpDir = join(process.cwd(), options.dir);
  const cwd = process.cwd();

  const config = loadConfig(bpDir);
  const files = generateAll(config);
  const generatedPaths = files.map(f => f.path);

  console.log('Regenerating platform files...');
  writeGeneratedFiles(files);

  // Cleanup stale files
  cleanupStaleFiles(cwd, generatedPaths);

  // Deploy OMP hook
  const hookDir = join(cwd, '.omp', 'hooks', 'pre');
  mkdirSync(hookDir, { recursive: true });
  writeFileSync(join(hookDir, 'bp.ts'), HOOK_TEMPLATE, 'utf-8');
  console.log('  ✓ .omp/hooks/pre/bp.ts');

  console.log(`✓ Update complete (${files.length + 1} files)`);
}
