/**
 * bp-update.test.ts — `bp update` stale cleanup tests
 *
 * T-6 RED: GIVEN stale generated and unrelated Codex files
 *          WHEN `bp update` runs
 *          THEN only stale generated entries are removed
 *               AND unrelated files still exist.
 *
 * Spec: specs/platform-gen/spec.md#codex-update-cleanup
 */

import { describe, it, expect, beforeAll, afterAll, beforeEach } from 'vitest';
import { execSync } from 'node:child_process';
import { existsSync, mkdirSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { tmpdir } from 'node:os';

const cliPath = join(process.cwd(), 'bin/cli.js');

describe('bp update — Codex safe stale cleanup (T-6)', () => {
  let testDir: string;
  let bpDir: string;

  beforeAll(() => {
    testDir = join(tmpdir(), `bp-update-codex-${Date.now()}`);
    mkdirSync(testDir, { recursive: true });
    bpDir = join(testDir, 'bp');
    execSync(`node ${cliPath} init --dir ${testDir} --yes`, {
      encoding: 'utf-8',
      cwd: testDir,
    });
  });

  afterAll(() => {
    rmSync(testDir, { recursive: true, force: true });
  });

  beforeEach(() => {
    // Start each test from a clean state — remove any codex/agents fixtures
    rmSync(join(testDir, '.codex'), { recursive: true, force: true });
    rmSync(join(testDir, '.agents'), { recursive: true, force: true });
  });

  it('removes stale `.codex/hooks.json` from a previous run', () => {
    // Seed a stale hooks.json — current generation no longer has it
    const codexDir = join(testDir, '.codex');
    mkdirSync(codexDir, { recursive: true });
    writeFileSync(join(codexDir, 'hooks.json'), '{"hooks": {}}', 'utf-8');

    // Drop codex from config so generateAll won't regenerate hooks.json
    const configPath = join(bpDir, 'config.yaml');
    let config = readFileSync(configPath, 'utf-8');
    config = config.replace(/platform:\n(?:  - [^\n]+\n)+/, 'platform:\n  - omp\n');
    writeFileSync(configPath, config, 'utf-8');

    execSync(`node ${cliPath} update --dir bp`, { encoding: 'utf-8', cwd: testDir });

    expect(existsSync(join(testDir, '.codex', 'hooks.json'))).toBe(false);
  });

  it('removes stale `.agents/skills/bp-archive-old/` skill directory', () => {
    // Seed a stale bp-* skill directory that is NOT in the current generation
    const staleSkillDir = join(testDir, '.agents', 'skills', 'bp-archive-old');
    mkdirSync(staleSkillDir, { recursive: true });
    writeFileSync(join(staleSkillDir, 'SKILL.md'), '# stale', 'utf-8');

    // Drop codex from config so generateAll won't regenerate it
    const configPath = join(bpDir, 'config.yaml');
    let config = readFileSync(configPath, 'utf-8');
    config = config.replace(/platform:\n(?:  - [^\n]+\n)+/, 'platform:\n  - omp\n');
    writeFileSync(configPath, config, 'utf-8');

    execSync(`node ${cliPath} update --dir bp`, { encoding: 'utf-8', cwd: testDir });

    expect(existsSync(staleSkillDir)).toBe(false);
  });

  it('preserves arbitrary `.codex/foo.txt` (not generated by us)', () => {
    // User-written file under .codex that bp does not own
    const codexDir = join(testDir, '.codex');
    mkdirSync(codexDir, { recursive: true });
    writeFileSync(join(codexDir, 'foo.txt'), 'user data', 'utf-8');

    execSync(`node ${cliPath} update --dir bp`, { encoding: 'utf-8', cwd: testDir });

    expect(existsSync(join(codexDir, 'foo.txt'))).toBe(true);
    expect(readFileSync(join(codexDir, 'foo.txt'), 'utf-8')).toBe('user data');
  });

  it('preserves non-bp skills in `.agents/skills/third-party/`', () => {
    // Skill not under the bp- namespace — must be left alone
    const thirdPartyDir = join(testDir, '.agents', 'skills', 'third-party');
    mkdirSync(thirdPartyDir, { recursive: true });
    writeFileSync(join(thirdPartyDir, 'SKILL.md'), '# third-party skill', 'utf-8');

    execSync(`node ${cliPath} update --dir bp`, { encoding: 'utf-8', cwd: testDir });

    expect(existsSync(join(thirdPartyDir, 'SKILL.md'))).toBe(true);
  });

  it('preserves current-generation codex files when codex is configured', () => {
    // Restore codex in config so generateAll WILL regenerate it
    const configPath = join(bpDir, 'config.yaml');
    let config = readFileSync(configPath, 'utf-8');
    if (!config.includes('- codex')) {
      config = config.replace(/platform:\n  - omp\n/, 'platform:\n  - omp\n  - codex\n');
      writeFileSync(configPath, config, 'utf-8');
    }
    execSync(`node ${cliPath} update --dir bp`, { encoding: 'utf-8', cwd: testDir });

    expect(existsSync(join(testDir, '.codex', 'hooks.json'))).toBe(true);
    // At least one current bp skill should be present
    expect(existsSync(join(testDir, '.agents', 'skills', 'bp-plan', 'SKILL.md'))).toBe(true);
  });
});

describe('bp update — Claude Code safe stale cleanup (T-4)', () => {
  let testDir: string;
  let bpDir: string;

  beforeAll(() => {
    testDir = join(tmpdir(), `bp-update-claude-${Date.now()}`);
    mkdirSync(testDir, { recursive: true });
    bpDir = join(testDir, 'bp');
    execSync(`node ${cliPath} init --dir ${testDir} --yes`, {
      encoding: 'utf-8',
      cwd: testDir,
    });
  });

  afterAll(() => {
    rmSync(testDir, { recursive: true, force: true });
  });

  beforeEach(() => {
    rmSync(join(testDir, '.claude'), { recursive: true, force: true });
  });

  it('removes stale `.claude/settings.json` from a previous run', () => {
    const claudeDir = join(testDir, '.claude');
    mkdirSync(claudeDir, { recursive: true });
    writeFileSync(join(claudeDir, 'settings.json'), '{"hooks": {}}', 'utf-8');

    // Drop claude-code from config so generateAll won't regenerate it
    const configPath = join(bpDir, 'config.yaml');
    let config = readFileSync(configPath, 'utf-8');
    config = config.replace(/platform:\n(?:  - [^\n]+\n)+/, 'platform:\n  - omp\n');
    writeFileSync(configPath, config, 'utf-8');

    execSync(`node ${cliPath} update --dir bp`, { encoding: 'utf-8', cwd: testDir });

    expect(existsSync(join(testDir, '.claude', 'settings.json'))).toBe(false);
  });

  it('removes stale `.claude/hooks/bp-claude-handler.mjs` from a previous run', () => {
    const claudeHooksDir = join(testDir, '.claude', 'hooks');
    mkdirSync(claudeHooksDir, { recursive: true });
    writeFileSync(join(claudeHooksDir, 'bp-claude-handler.mjs'), '# stale', 'utf-8');

    const configPath = join(bpDir, 'config.yaml');
    let config = readFileSync(configPath, 'utf-8');
    config = config.replace(/platform:\n(?:  - [^\n]+\n)+/, 'platform:\n  - omp\n');
    writeFileSync(configPath, config, 'utf-8');

    execSync(`node ${cliPath} update --dir bp`, { encoding: 'utf-8', cwd: testDir });

    expect(existsSync(join(testDir, '.claude', 'hooks', 'bp-claude-handler.mjs'))).toBe(false);
  });

  it('preserves arbitrary `.claude/notes.txt` (not generated by us)', () => {
    const claudeDir = join(testDir, '.claude');
    mkdirSync(claudeDir, { recursive: true });
    writeFileSync(join(claudeDir, 'notes.txt'), 'user notes', 'utf-8');

    execSync(`node ${cliPath} update --dir bp`, { encoding: 'utf-8', cwd: testDir });

    expect(existsSync(join(testDir, '.claude', 'notes.txt'))).toBe(true);
    expect(readFileSync(join(testDir, '.claude', 'notes.txt'), 'utf-8')).toBe('user notes');
  });

  it('preserves current-generation claude files when claude-code is configured', () => {
    const configPath = join(bpDir, 'config.yaml');
    let config = readFileSync(configPath, 'utf-8');
    if (!config.includes('- claude-code')) {
      config = config.replace(/platform:\n  - omp\n/, 'platform:\n  - omp\n  - claude-code\n');
      writeFileSync(configPath, config, 'utf-8');
    }
    execSync(`node ${cliPath} update --dir bp`, { encoding: 'utf-8', cwd: testDir });

    expect(existsSync(join(testDir, '.claude', 'settings.json'))).toBe(true);
    expect(existsSync(join(testDir, '.claude', 'hooks', 'bp-claude-handler.mjs'))).toBe(true);
  });
});
