/**
 * OMP Extension template — string-constant source of truth.
 *
 * The string exported as `EXTENSION_SOURCE` is the full self-contained
 * TypeScript source of the generated `.omp/extensions/bp/index.ts` file.
 * `src/integrations/omp/extension.ts` reads this constant and emits it
 * verbatim — no inline string literal duplicates this content.
 *
 * Filled-in by Wave 3 (T-26..T-37). The placeholder below is the minimal
 * shape every shipped Extension must satisfy: a `default` export that
 * OMP's Extension API can invoke with `(api) => void`.
 */

export const EXTENSION_SOURCE = `/**
 * bp OMP Extension - generated by bp update. Do not edit manually.
 *
 * Provides OMP with:
 *   - session_start:  <bp-context> block + role-augmented payload
 *   - before_agent_start: workflow-state custom message
 *   - context:        post-compaction reverse-scan re-injection
 */
export default function bpExtension(api) {
  api.on("session_start", function (event, ctx) { /* filled by T-26..T-29 */ });
  api.on("before_agent_start", function (event, ctx) { /* filled by T-30 */ });
  api.on("context", function (event, ctx) { /* filled by T-31..T-32 */ });
}
`;
