/**
 * OMP legacy-shim template — string-constant source of truth.
 *
 * The string exported as `SHIM_SOURCE` is the full self-contained
 * TypeScript source of the generated `.omp/hooks/pre/bp.ts` file. The
 * shim re-exports the default export from the Extension so OMP runtimes
 * that don't yet support the Extension API still load the same logic.
 */

export const SHIM_SOURCE = `// Generated by bp update. Do not edit manually.
// Legacy hook shim for OMP runtimes without Extension support.
export { default } from "../extensions/bp/index.js";
`;
